# Generated by Django 4.1.7 on 2023-04-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass1name', models.CharField(max_length=100)),
                ('pass1age', models.CharField(max_length=10)),
                ('pass1berth_opt', models.CharField(default='SL', max_length=100)),
                ('pass2name', models.CharField(blank=True, max_length=100, null=True)),
                ('pass2age', models.CharField(blank=True, max_length=100, null=True)),
                ('pass2berth_opt', models.CharField(blank=True, max_length=100, null=True)),
                ('pass3name', models.CharField(blank=True, max_length=100, null=True)),
                ('pass3age', models.CharField(blank=True, max_length=100, null=True)),
                ('pass3berth_opt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.IntegerField()),
                ('train_name', models.CharField(max_length=100)),
                ('train_source', models.CharField(max_length=100)),
                ('train_dest', models.CharField(max_length=100)),
                ('train_departure', models.CharField(max_length=100)),
                ('train_arrival', models.CharField(max_length=100)),
                ('run_d', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
