# Generated by Django 4.1.7 on 2023-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookticket',
            name='id',
        ),
        migrations.AddField(
            model_name='bookticket',
            name='pnr_number',
            field=models.IntegerField(default=2455767589, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
