# Generated by Django 4.1.7 on 2023-04-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_register_id_bookticket_datejourney_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookticket',
            name='trainNumber',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='pass2age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='pass3age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
