# Generated by Django 4.1.7 on 2023-04-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bookticket_trainnumber_alter_bookticket_pass2age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookticket',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
